


	76:     name = _("[jason]"),
	97: name = "Lexie",
	98: display_name = _("[lexie]"), 
	122: name = "Marvin",
	123: display_name = _("[marvin]"), 
	146: name = "Michelle",
	147: display_name = _("[boulangere]"), 
	172: name = "Marya",
	173: display_name = _("[pute]"), 
	198: name = "Feng",
	199: display_name = _("[feng]"), 
	224: name = "Erik",
	225: display_name = _("[erik]"), 
	249: name = "Rita",
	250: display_name = _("[rita]"), 
	274: name = "Alex",
	275: display_name = _("[alex]"), 
	299: name = "Kate",
	300: display_name = _("[kate]"), 
	324: name = "Madison",
	325: display_name = _("[madison]"),
	349: name = "Vanille",
	350: display_name = _("[vanille]"),
	374: name = "Amal",
	375: display_name = _("[amal]"),
	399: name = "Salai",
	400: display_name = _("[salai]"),
	424: name = "Greta",
	425: display_name = _("[greta]"),
	449: name = "Julienne",
	450: display_name = _("[julienne]"),
	474: name = "Carolina",
	475: display_name = _("[carolina]"),
	499: name = "Guliana",
	500: display_name = _("[guliana]"),
	524: name = "Megan",
	525: display_name = _("[kateb]"),
	548: name = "Nicole",
	549: display_name = _("[nicole]"),
	572: name = "Jennifer",
	573: display_name = _("[jennifer]"),
	596: name = "Melissa",
	597: display_name = _("[melissa]"),
	620: name = "Monique",
	621: display_name = _("[monique]"),
	644: name = "Sandra",
	645: display_name = _("[sandra]"),
	668: name = "Nina",
	669: display_name = _("[nina]"),
	692: name = "Mizuki",
	693: display_name = _("[mizuki]"),
	716: name = "Mia",
	717: display_name = _("[mia]"),
	740: name = "Ameria",
	741: display_name = _("[ameria]"),
	764: name = "Arnold",
	765: display_name = _("[arnold]"),
	788: name = "Rosie",
	789: display_name = _("[rosie]"),
	813: name = "Narcisa",
	814: display_name = _("[narcisa]"),
	835: name = "true_Sandra",
	836: display_name = _("[true_sandra]"),
	857: name = "Evelyn",
	858: display_name = _("[evelyn]"),
	879: name = "Elise",
	880: display_name = _("[elise]"),



###################################################################################################


# NAME ############
("Relya") 
("Lirael") 
("Vivianne") 
("Vivi") 
("Kaela") 
("Sylph") 
("Knight")
("Fiona") 
("Melfa") 
("Fraya")
("Velera")
("Vel")
("Helen")
("Lynn") 
("Soul Tice")
("Salvia")
("Orc Sensei")
("Drakeford")
("Rod Malvine")
("Jahmet")
("Varian Ashcroft")
("Jin Nagawi")
("Almera")
("Magnar")
("Richard")
("Zelmir")
("Kena")
("guard")
("Everyone")
("Zack")
("Charot")
("Rean")
("Lina")
("Tyra")
("Sora (Tyra)")
("Geen")
("Marl")
("Vaelkris")
("Thalia")
("Vega")
("Tress")
("Rode")
("Zheros")
("Myrranel")  
("Urghas")
("Rocky")
("Kreg")
("Pyrel")
("Gill")
("Moritz")
("Modgarr")

###################################################################################################

annie
nancy
dalia
penelope
alex
luna
nova
calypso
maat
penny
Alexandra

Arsael
Arsa
Alia
Noel
Clara
Cand
Samuel
Nael
Ellen
Sarah
Luna
Stephanie
Jacky
Gabriel
Michael
Matt
Amy
Tessah
Ciarar
Ren
Chadley
Emma
Takeshi
Carol
Claire
Fabiano
Styx
Jason
Misty
Albere
Marth
Nathan
Blake
Pierre

###################################################################################################

Eliza
Maya
Shane
Oren
Sabrin
Flynn
Gibson
Ellen
Asta
Beth
Mina
Taron
Lord Alaric
Cassian
Rammus
Raden
King Benne
Merid
Amelia
Sylvia
Frida
Gwen
Christine
Quinn
Adeline
Bren
t
Malanthe
Maia
Gaia
Balthazar
Castiel
Andromed
Lucid
Raze
Malpheo
n
Kinesis
Azir
Luriel
Ariel
Zerachie
Selena
Meredith
Samara
Fiona
Anna
Kaspin
Jasmin
Zefra
alerie
Inna
Eric
Christa
Monica
Geskir
Gaius
Gaan
Richard
Sarah
Lailah
Kelly
Edward
Maggie
Pearl
Kira
Diana
Echo
Marah
Suji
Zyra
Vex
Maze
Sakari
Miyo
a
Kish
Tatiana
Riven
Orianna
Ria
Alyze
Sivah
Sewah
Tuhi
Aiyo
Rora
Leah
Borri
Dalen
Alice
Sylph
Rin
Cassandra
Rose
Nielah
Lina
Celin
Lux
Lilith
Victoria
Nihlu
Lucien
Irene
Viperia
Alana
e
Circ
Envy
Tazzy
Cheya